### ISSUE TITLE
ETQ 'appli', il y a beaucoup d'erreur sur la recheche concernant le ROME

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#1706]
### :bug: Le problème

On prends beaucoup d'erreurs sur la recherche concernant des ROME non trouvé :

```
_message: "Unhandled Error"
constructorName: "Error"
message: "No Rome code found for appellation codes 403741"
name: "Error"
request: {
  "path": "/immersion-offers",
  "method": "GET"
}
stack: "Error: No Rome code found for appellation codes 403741
    at PgEstablishmentAggregateRepository.<anonymous> (/app/back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.js:678:19)
    at Generator.next (<anonymous>)\n    at fulfilled (/app/back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
type: "Unknown Error"
```

### :footprints: Étapes pour reproduire

Je ne sais pas. Il faut investiguer....

### :dart: Comportement attendu

Ne pas prendre ces erreurs.

On peut ajouter les quelques codes ROME manquants dans notre base.

**Comment by 3lodi3** [comment]
POur préparer #1701
